### ISSUE TITLE
Order Summary Improvements and Making it similar to EventBrite

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2993]
There is scope for several improvements in Tax Modal generated at `Order Checkout` -:
 
* [x] Include `Ticket Price` in row of every ticket
* [x] For a `Free Ticket` adding tax does not make any sense , Remove the `Column for Free Ticket`.
* [x] Fix the alignment issue in `Order Checkout`
* [x] Remove the `Discount Column` if no `Discount Code` is applied
* [ ] Show `Subtotal` inclusive of `Individual Ticket with Tax Rate`
* [x] Columns of `Payment Dialogue` are wrongly placed , Use standard order as in `Eventbrite` or any E-Commerce Site.

#### Screenshot -:

<img width="691" alt="Screenshot 2019-05-23 at 4 19 45 PM" src="https://user-images.githubusercontent.com/44091822/58247680-da62d080-7d77-11e9-8fa9-cafc63e162a9.png">

**Comment by kushthedude** [comment]
@CosmicCoder96 @uds5501 @shreyanshdwivedi What you guys think about it ?

**Comment by mariobehling** [comment]
How is this done in Eventbrite? Please check and let's learn from that.

**Comment by Anupam-dagar** [comment]
@kushthedude since the issue is divided into 6 parts, I would like to take 1 or 2 of them to resolve.

**Comment by kushthedude** [comment]
@Anupam-dagar It would be great if you can help me with subtotal part

**Comment by Anupam-dagar** [comment]
@kushthedude I guess for free tickets, writing "Not Applicable" in tax column will be much better.

**Comment by uds5501** [comment]
@kushthedude just saying, can you please take a look at how is this implemented in eventbrite and post a screen shot of the same?

**Comment by kushthedude** [comment]
> @kushthedude just saying, can you please take a look at how is this implemented in eventbrite and post a screen shot of the same?

@uds5501 I have seen the one in eventbrite , Regarding the SS here are they :- 

### FREE -:
<img width="1440" alt="Screenshot 2019-06-08 at 10 46 28 AM" src="https://user-images.githubusercontent.com/44091822/59142353-b55a9880-89da-11e9-9837-ef9112a21ff1.png">

### Paid-:
<img width="1440" alt="Screenshot 2019-06-08 at 10 47 36 AM" src="https://user-images.githubusercontent.com/44091822/59142367-e1761980-89da-11e9-90af-f3bab931ccb9.png">

`The subtotal is inclusive of tax and fee for individual ticket`

**Comment by kushthedude** [comment]
And I have incorporated similar changes in #3079  -:
`Like when there is no Discount , There is no column of Discount Code, Ordering of columns and etc`

**Comment by uds5501** [comment]
@kushthedude and what about the exclusive taxes? just put these on top so that breaking down this issue into subissue would become easier!

**Comment by kushthedude** [comment]
> @kushthedude and what about the exclusive taxes? just put these on top so that breaking down this issue into subissue would become easier!

Can you elaborate ?

**Comment by uds5501** [comment]
@kushthedude there can be total 2 use cases in which this issue should be broken down.
- The case where taxes are inclusive.
- The case where taxes are added on top of the ticket price.

AFAIK, eventbrite handled both the cases differently. We are just refining according to the case 1 which, I don't think should be the case if we are aiming a likelihood to the source.

@shreyanshdwivedi  views?

**Comment by kushthedude** [comment]
> @kushthedude there can be total 2 use cases in which this issue should be broken down.
> 
> * The case where taxes are inclusive.
> * The case where taxes are added on top of the ticket price.
> 
> AFAIK, eventbrite handled both the cases differently. We are just refining according to the case 1 which, I don't think should be the case if we are aiming a likelihood to the source.
> 
> @shreyanshdwivedi views?
;

I think you got the wrong idea , For the case 2 , When tax is added on the ticket price , We show a column price of ticket and Subtotal( which does not count the tax in it ) , 

And as far as point 1 Considered I was thinking to open a new issue and in subscript of ticket we can say` All Tax Inclusive`
@uds5501 What you say ?

**Comment by Anupam-dagar** [comment]
@kushthedude can you post a screenshot for the payment dialogue
