### ISSUE TITLE
Improvements in Browse Events Section

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3122]
**Describe the bug**

- [x] Mobile View does not redirect to the browse events section.
- [x] No pagination in the section.
- [x] Hide `Filters` for the mobile view as done in `Event Brite`.
- [ ] Add an Option to `Hide/Unhide` Map for Small Screens

**Comment by uds5501** [comment]
@kushthedude are you working on other two issues?, the hiding filters and map hide/unhide part?

**Comment by kushthedude** [comment]
@uds5501 No , Feel free if you want to take it

**Comment by uds5501** [comment]
@kushthedude Okay, will take a look
