### ISSUE TITLE
Add Pro-Event Features for Call for Speakers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4511]
Add the following feature details
* [ ] Add Pro-Event Cost option with a tab under https://eventyay.com/admin/settings/
* [ ] Add option to upgrade event to Pro-Event by admins in table at https://eventyay.com/admin/events/
* [ ] Create "Pro Event" option in event wizard
* [ ] Create "Upgrade to Pro Event" for existing events similar to papercall

Implement Limits of Standard Events vs. Pro Event
* [ ] Pro Event: Enable Video Feature
* [ ] Pro Event: Enable more than 200 submissions
* [ ] Pro Event: Enable custom form questions

Other details
* [ ] Allow standard events with up to 200 submissions and request an upgrade to Pro-Events afterwards
   * [ ] Create error message for speakers after 200 submissions "This event requires an upgrade to accept additional submissions."
   * [ ] Create a 1. system email, 2. a notification, 3. a note on the event management page ones 200 submissions are reached requiring an upgrade "Please upgrade to a Pro Event to receive more submissions. Click here to upgrade."
* [ ] Create invoices for Pro-Event payments
